language: haskell

git:
  depth: 5

cabal: "2.4"
ghc: "8.8.4"

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.8.4
  
install:
  - |
    curl -sSL https://get.haskellstack.org/ | sh
    stack --version
    stack build --system-ghc \
          --test --no-run-tests \
          --ghc-options=-Werror

script:
  - stack test --system-ghc

notifications:
  email: false
